apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: apache-demo

  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://github.com/shahidterra65/argocd_nginx.git

    targetRevision: main

    path: apache

  destination:

    server: https://kubernetes.default.svc

    namespace: apache

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

      - CreateNamespace=true


 