apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx 
  namespace: web 
  labels: 
    app: nginx 
spec: 
  replicas: 2  # Starting with 2 replicas 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
        - name: nginx 
          image: nginx:1.25-alpine  # Lightweight Alpine image 
          ports: 
            - containerPort: 80 
          resources: 
            requests: 
              memory: "64Mi" 
              cpu: "250m" 
            limits: 
              memory: "128Mi"   
              cpu: "500m" 
          readinessProbe: 
            httpGet: 
              path: / 
              port: 80 
            initialDelaySeconds: 5 
            periodSeconds: 10 
          livenessProbe: 
            httpGet: 
              path: / 
              port: 80 
            initialDelaySeconds: 15 
            periodSeconds: 20 