apiVersion: v1 
kind: Service 
metadata: 
  name: nginx 
  namespace: web 
  labels: 
    app: nginx 
spec: 
  type: NodePort 
  selector: 
    app: nginx 
  ports: 
    - name: http 
      port: 80        # Internal cluster port 
      targetPort: 80  # Container port 
      nodePort: 30081 # External access port 